### ISSUE TITLE
Add node location in monitoring data

### ISSUE THREAD

**Issue by herry13** [fruit-testbed/fruit-agent#5]
Node location can be resolved using its external IP address. The steps are:

1. get external IP address from ifconfig.me: `curl ifconfig.me`, or https://www.ipify.org
2. resolve location of IP using ipstack.com: `http://api.ipstack.com/<ip>?access_key=<key>`

**Comment by herry13** [comment]
implemented in db1c03da4de13b8c8b3a19d9262aa430042e3cf1 and 11140c3e7ccfa896cfb9f2251169c5cb6cf4032c

**Comment by herry13** [comment]
@pjb304 now the console web page should show the node location.

**Comment by pjb304** [comment]
Very nice :)
